magnolia_booking/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='homepage'),
]

magnolia_booking/magnolia_booking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', 'core')),
    path('rooms/', include('rooms.urls', 'rooms')),
    path('reservations/', include('reservations.urls', 'reservations')),
]

magnolia_booking/reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path('request_reservation/', views.BookingWizardView.as_view(), name="request_reservation"),
    # path('request_room/search/', views.booking_search, name="booking_search"),
    # path('request_room/results/', views.booking_result, name="booking_result"),
    # path('request_room/confirm/', views.booking_confirm, name="booking_confirm"),
    # path('reserve/', views.make_reservation, name="make_reservation"),
    # path('reserve/<int:pk>', views.make_reservation, name="make_reservation_select_room"),
    path('success/', views.reservation_success, name="reservation_success"),
]

magnolia_booking/rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'

urlpatterns = [
    path('all/', views.room_list, name='room-list'),
    path('detail/<int:room_id>/', views.room_detail, name='room-detail'),
]

magnolia_booking/core/models.py
from django.db import models

# Create your models here.

# class Reservation(models.Model):
#     room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='rooms')
#     group_size = models.IntegerField()
#     check_in = models.DateField()
#     check_out = models.DateField()
#
#     def __str__(self):
#         return self.pk

magnolia_booking/core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    home_index_context = {
        'title': 'Home'
    }
    return render(request=request,
                  template_name='core/index.html',
                  context=home_index_context)

magnolia_booking/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <title>{% block title %}{% endblock %} | Magnolia</title>

        <style>
            :root {
                --primary: #59359a;
                --secondary: #c5b3e6;
                --soft-white: #fcedf2;
                --primary-contrast: #ffffff;
                --hero-overlay: rgba(89, 53, 154, 0.45);
            }

            body {
                background: url({% static 'images/hero.jpg' %}) center/cover no-repeat;
            }

            .custom-background {
                background-color: rgba(161, 161, 161, 0.8);
            }
        </style>
    </head>
    <body>
        {% include 'core/navbar.html' %}

        <div class="container w-lg mx-auto custom-background">
            {% block content %}
            {% endblock %}
        </div>

        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

magnolia_booking/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}

    <div class="container-fluid hero-section d-flex justify-content-center align-items-center">
        <div class="hero-content">
            <h1 class="display-4 fw-bold mb-3">Your Perfect Getaway in Macedonia</h1>
            <h2 class="mb-4">Relax, Unwind, and Enjoy the Tranquility of Our Garden Retreat</h2>
            <p class="fs-4">Escape to a peaceful haven where comfort meets nature. Our cozy rooms
                are designed for groups of all sizes—whether you're traveling as a
                couple, a small family, or a group of friends. Nestled among beautiful
                palm trees in a serene garden, our rooms offer the perfect space to
                relax and recharge. Let the perfect weather and tranquil surroundings
                help you leave your worries behind and embrace the peaceful rhythm of
                life.</p>
            <a href="{% url 'rooms:room-list' %}" class="btn btn-secondary btn-lg mt-4">View Our Rooms</a>
            <a href="{% url 'reservations:request_reservation' %}" class="btn btn-primary btn-lg mt-4">Book Your Stay</a>
        </div>
    </div>

{% endblock %}

magnolia_booking/core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'core:homepage' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Rooms
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'rooms:room-list' %}">All Rooms</a></li>
                        <li><hr class="dropdown-divider"></li>
<!--                        Find a way to implement room.id dynamically instead of hard-coding-->
                        <li><a class="dropdown-item" href="{% url 'rooms:room-detail' 7 %}">Sunset Studio</a></li>
                        <li><a class="dropdown-item" href="{% url 'rooms:room-detail' 8 %}">Sunrise Studio</a></li>
                        <li><a class="dropdown-item" href="{% url 'rooms:room-detail' 9 %}">Palm Apartment</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>